const Language = { "English" :{
                        "settings" : "Settings",
                        "signin" : "Sign In",
                        "signup" : "Sign Up",
                        "username" : "USERNAME",
                        "password" : "PASSWORD",
                        "login" : "Login",
                        "forgot" : "Forgot Password ?",
                        "fname" : "Full Name",
                        "email" : "EMAIL",
                        "pnumber" : "Phone Number",
                        "continue" : "Continue",
                        "haveacc" : "Already Have an Account ? ",
                        "pagain" : "Password Again",
                        "submit" : "Submit",
                        "check" : "Check you email, You will receive a code",
                        "code" : "Code",
                        "npass" : "NEW PASSWORD",
                        "npassagain" : "NEW PASSWORD AGAIN",
                        "send" : "Send",
                        "cancel" : "Cancel and Sign In",
                        "back" : "Go Back",
                        "display" : "Display Mode",
                        "dark" : "DARK",
                        "light" : "LIGHT",
                        "language" : "Language",
                        "english" : "English",
                        "french" : "Francais",
                        "Arabe" : "Arabe",
                        "report" : "REPORT",
                        "about" : "About US",
                        "ysearch" : "Search From Youtube",
                        "search" : "Search",
                        "total" : "My Total Songs",
                        "songs" : "Songs",
                        "editacc" : "Edit Account",
                        "reportbg" : "Report Bug",
                        "logout" : "Log Out",
                        "image" : "Update Image",
                        "path" : "Update File Path",
                        "save" : "Save Changes",
                        "pup" : "Update Password",
                        "delete" : "Delete Account", 
                        },
                        "French" : {
                            "settings" : "Parametre",
                            "signin" : "S'identifier",
                            "signup" : "S'inscrire",
                            "username" : "Nom D'utilisateur",
                            "password" : "Mot de passe",
                            "login" : "S'inscrire",
                            "forgot" : "Oublié le mot de passe ?",
                            "fname" : "Full Name",
                            "email" : "EMAIL",
                            "pnumber" : "Phone Number",
                            "continue" : "EMAIL",
                            "haveacc" : "Already Have an Account ? ",
                            "pagain" : "Password Again",
                            "submit" : "Submit",
                            "check" : "Check you email, You will receive a code",
                            "code" : "Code",
                            "npass" : "NEW PASSWORD",
                            "npassagain" : "NEW PASSWORD AGAIN",
                            "send" : "Send",
                            "cancel" : "Cancel and Sign In",
                            "back" : "Go Back",
                            "display" : "Display Mode",
                            "dark" : "DARK",
                            "light" : "LIGHT",
                            "language" : "Language",
                            "english" : "English",
                            "french" : "Francais",
                            "Arabe" : "Arabe",
                            "report" : "REPORT",
                            "about" : "About US",
                            "ysearch" : "Search From Youtube",
                            "search" : "Search",
                            "total" : "My Total Songs",
                            "songs" : "Songs",
                            "editacc" : "Edit Account",
                            "reportbg" : "Report Bug",
                            "logout" : "Log Out",
                            "image" : "Update Image",
                            "path" : "Update File Path",
                            "save" : "Save Changes",
                            "pup" : "Update Password",
                            "delete" : "Delete Account", 
                        },

                        "Arabe" : {
                            "settings" : "Parametre",
                            "signin" : "S'identifier",
                            "signup" : "S'inscrire",
                            "username" : "Nom D'utilisateur",
                            "password" : "Mot de passe",
                            "login" : "S'inscrire",
                            "forgot" : "Oublié le mot de passe ?",
                            "fname" : "Full Name",
                            "email" : "EMAIL",
                            "pnumber" : "Phone Number",
                            "continue" : "EMAIL",
                            "haveacc" : "Already Have an Account ? ",
                            "pagain" : "Password Again",
                            "submit" : "Submit",
                            "check" : "Check you email, You will receive a code",
                            "code" : "Code",
                            "npass" : "NEW PASSWORD",
                            "npassagain" : "NEW PASSWORD AGAIN",
                            "send" : "Send",
                            "cancel" : "Cancel and Sign In",
                            "back" : "Go Back",
                            "display" : "Display Mode",
                            "dark" : "DARK",
                            "light" : "LIGHT",
                            "language" : "Language",
                            "english" : "English",
                            "french" : "Francais",
                            "Arabe" : "Arabe",
                            "report" : "REPORT",
                            "about" : "About US",
                            "ysearch" : "Search From Youtube",
                            "search" : "Search",
                            "total" : "My Total Songs",
                            "songs" : "Songs",
                            "editacc" : "Edit Account",
                            "reportbg" : "Report Bug",
                            "logout" : "Log Out",
                            "image" : "Update Image",
                            "path" : "Update File Path",
                            "save" : "Save Changes",
                            "pup" : "Update Password",
                            "delete" : "Delete Account", 
                        }
                    
                    


}

export default Language